strictness: high
test-warnings: true
doc-warnings: false

ignore-paths:
  - build
  - tests
  - skel_metamodel

pycodestyle:
  options:
    max-line-length: 100

pylint:
  disable:
    - unsubscriptable-object

mccabe:
  run: true
