# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  workflow_dispatch:
    inputs:
      pypiRepository:
        description: 'Pypi repository (pypi or testpypi)'
        required: true
        default: testpypi
      pypiUsername:
        description: 'Pypi username'
        required: true
      pypiPassword:
        description: 'Pypi password'
        required: true

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ github.event.inputs.pypiUsername }}
        TWINE_PASSWORD: ${{ github.event.inputs.pypiPassword }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload --repository ${{ github.event.inputs.pypiRepository }} dist/*
